name: Test Action
description: Testing Actions

inputs:
  config:
    description: 'The path to the config file'
    required: true
    default: 'config.hcl'
#  TFE_TOKEN:
#    description: 'The token for interacting with TFC'
#    required: true
#  future: need to specify TFC URL, to allow for eu TFC

runs:
  using: "composite"
  steps:

  - name: Set up Go
    uses: actions/setup-go@v5
    with:
      go-version: '1.21'

  - name: Run
    shell: bash
    run:
      cd ${{ github.action_path }}/script &&
      go run . --config config.hcl