name: Test Action
description: Testing Actions

inputs:
  tfe-token:
    description: 'The token for interacting with TFC'
    required: true
  config:
    description: 'The path to the config file'
    required: true
    default: 'config.hcl'
#  future: need to specify TFC URL, to allow for eu TFC

runs:
  using: "composite"
  steps:

  - name: Set up Go
    uses: actions/setup-go@v5
    with:
      go-version: '1.21'
      cache-dependency-path: "${{ github.action_path }}/script"

  - name: Run
    shell: bash
    env:
      TFE_TOKEN: ${{ inputs.tfe-token }}
    run:
      cd ${{ github.action_path }}/script &&
      go run . --config ${{ github.workspace }}/${{ inputs.config }}