name: Test Action
description: Testing Actions

runs:
  using: "composite"
  steps:
  - name: Test Step
    shell: bash
    run:
      echo "Hello, World!" ;
      echo ;
      env ;
      echo ;
      pwd ;
      echo ;
      ls -lah